languageCode = "en-us"
copyright = "All rights reserved."
theme = "noteworthy"
paginate = 10
title = "Tai's Blog"
subtitle = ""
keywords = ""
googleAnalytics = "UA-83412074-6"

[permalinks]
	posts = "/:filename"

[author]
	name = "Le Loc Tai"

[[menu.main]]
	identifier = "main-site"
	name = "Main site"
	url = "https://leloctai.com"

[params]
	email="mailto:contact@leloctai.com"
	twitter="https://twitter.com/LeLocTai"
	reddit="https://www.reddit.com/user/leloctai/?sort=top"

[related]
	threshold = 80
	includeNewer = true
	toLower = true
[[related.indices]]
	name = "keywords"
	weight = 100
[[related.indices]]
	name = "tags"
	weight = 80
[[related.indices]]
	name = "date"
	weight = 10

[markup.goldmark.renderer]
	unsafe = true

[markup]
	[markup.tableOfContents]
		startLevel = 2
		endLevel = 2
		ordered = true

	[markup.highlight]
		codeFences = true
		guessSyntax = true
		hl_Lines = ""
		lineNoStart = 1
		lineNos = false
		lineNumbersInTable = true
		noClasses = true
		style = "dracula"
		tabWidth = 3

[privacy]
	[privacy.googleAnalytics]
		anonymizeIP = true
		useSessionStorage = true
	[privacy.instagram]
		simple = true
	[privacy.twitter]
		enableDNT = true
		simple = true
	[privacy.youtube]
		privacyEnhanced = true
