languageCode = "en-us"
copyright = "All rights reserved."
theme = "noteworthy"
paginate = 10
title = "Tai"
subtitle = ""
keywords = ""
googleAnalytics = "UA-83412074-6"

[permalinks]
	posts = "/:slug"

[author]
	name = "Le Loc Tai"
	
[[menu.main]]
	identifier = "main-site"
	name = "Main site"
	url = "https://leloctai.com"

[related]
	threshold = 80
	includeNewer = true
	toLower = true
[[related.indices]]
	name = "keywords"
	weight = 100
[[related.indices]]
	name = "tags"
	weight = 80
[[related.indices]]
	name = "date"
	weight = 10


[markup.goldmark.renderer]
	unsafe = true

[markup]
	[markup.tableOfContents]
		startLevel = 2
		endLevel = 2
		ordered = true
		
	[markup.highlight]
		codeFences = true
		guessSyntax = false
		hl_Lines = ""
		lineNoStart = 1
		lineNos = false
		lineNumbersInTable = true
		noClasses = true
		style = "monokailight"
		tabWidth = 3

[privacy]
	[privacy.googleAnalytics]
		anonymizeIP = true
		useSessionStorage = true
	[privacy.instagram]
		simple = true
	[privacy.twitter]
		enableDNT = true
		simple = true
	[privacy.youtube]
		privacyEnhanced = true

# [params]  
# 	# dir name of your blog content (default is `content/posts`)
# 	contentTypeName = "posts" 
# 	# ["orange", "blue", "red", "green", "pink"]
# 	themeColor = "blue"
# 	# if you set this to 0, only submenu trigger will be visible
# 	showMenuItems = 5
# 	showLanguageSelector = false
# 	fullWidthTheme = false
# 	centerTheme = true

# 	# set a custom favicon (default is a `themeColor` square)
# 	# favicon = "favicon.ico"

# 	# set all headings to their default size (depending on browser settings)
# 	# it's set to `true` by default
# 	oneHeadingSize = false

# [params.logo]
# 	logoText = "Tai's Blog"
# 	logoHomeLink = "/"

