build:
  publish: 'public'
  command: 'hugo --gc --minify --verbose'
  environment:
    - HUGO_VERSION: '0.78.2'
    - HUGO_ENV: 'production'

headers:
  - for: '*.webmanifest'
    values:
      Content-Type: application/manifest+json; charset=UTF-8
  - for: /index.xml
    values:
      Access-Control-Allow-Origin: '*'
      Content-Type: application/rss+xml

redirects:
  - from: 'https://tai-blog.netlify.com'
    to: 'https://blog.leloctai.com'
    status: 200
    force: true
  - from: 'https://preview--tai-blog.netlify.com'
    to: 'https://preview--blog.leloctai.com'
    status: 200
    force: true
