[build]
publish = "public"
command = "hugo --gc --minify --verbose"

[context.production.environment]
HUGO_VERSION = "0.78.2"
HUGO_ENV = "production"

[[headers]]
for = "*.webmanifest"
[headers.values]
	Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
for = "/index.xml"
[headers.values]
	Content-Type = "application/rss+xml"
	Access-Control-Allow-Origin = "*"

[[redirects]]
from = "https://tai-blog.netlify.com"
to = "https://blog.leloctai.com"
status = 200
force = true

[[redirects]]
from = "https://preview--tai-blog.netlify.com"
to = "https://preview--blog.leloctai.com"
status = 200
force = true